export const TYPOGRAPHY_TOKENS = {
  fontFamilyDisplay: "var(--font-family-display)",
  fontFamilyBody: "var(--font-family-body)",
  headingXl: "var(--font-size-heading-xl)",
  headingLg: "var(--font-size-heading-lg)",
  headingMd: "var(--font-size-heading-md)",
  title: "var(--font-size-title)",
  bodyMd: "var(--font-size-body-md)",
  bodySm: "var(--font-size-body-sm)",
  caption: "var(--font-size-caption)",
  micro: "var(--font-size-micro)",
  letterSpacingDisplayHero: "var(--letter-spacing-display-hero)",
  letterSpacingBody: "var(--letter-spacing-body)",
  letterSpacingCaption: "var(--letter-spacing-caption)",
  letterSpacingMicro: "var(--letter-spacing-micro)",
  lineHeightTightest: "var(--line-height-tightest)",
  lineHeightTight: "var(--line-height-tight)",
  lineHeightNormal: "var(--line-height-normal)",
  lineHeightRelaxed: "var(--line-height-relaxed)",
  fontWeightRegular: "var(--font-weight-regular)",
  fontWeightMedium: "var(--font-weight-medium)",
  fontWeightSemibold: "var(--font-weight-semibold)",
  fontWeightBold: "var(--font-weight-bold)"
} as const;

export const SEMANTIC_COLOR_TOKENS = {
  background: "rgb(var(--color-bg-canvas))",
  text: "rgb(var(--color-fg-default))",
  surface: "rgb(var(--color-bg-surface))",
  surfaceElevated: "rgb(var(--color-bg-surface-raised))",
  border: "rgb(var(--color-border-default))",
  muted: "rgb(var(--color-fg-muted))",
  subtle: "rgb(var(--color-fg-subtle))",
  primary: "rgb(var(--color-accent-primary))",
  link: "rgb(var(--color-accent-link))",
  linkDark: "rgb(var(--color-accent-link-dark))",
  primaryText: "rgb(var(--color-fg-on-accent))",
  success: "rgb(var(--color-feedback-success))",
  successText: "rgb(var(--color-fg-on-success))",
  warning: "rgb(var(--color-feedback-warning))",
  warningText: "rgb(var(--color-fg-on-warning))",
  danger: "rgb(var(--color-feedback-danger))",
  dangerText: "rgb(var(--color-fg-on-danger))",
  info: "rgb(var(--color-feedback-info))",
  infoText: "rgb(var(--color-fg-on-info))"
} as const;
